# Generated by TwinMatch market-readiness hardening.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressvault",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addressvault",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addressvault",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addressvault",
            name="district",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addressvault",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="addressvault",
            name="phone_masked",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="giftproduct",
            name="supplier",
            field=models.CharField(
                choices=[("amazon", "Amazon"), ("ciceksepeti", "Çiçeksepeti")],
                max_length=32,
            ),
        ),
    ]
