# Generated by Django 5.1.15 on 2026-06-23 07:13

import django.db.models.deletion
import pgvector.django.vector
import pgvector.django.extensions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('education', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('zodiac_sign', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('smoking', models.CharField(max_length=32)),
                ('wants_children', models.CharField(max_length=32)),
                ('marital_status', models.CharField(max_length=64)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_key', models.CharField(max_length=512)),
                ('cdn_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_key', models.CharField(max_length=512)),
                ('cdn_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
