# Generated by Django 5.1.15 on 2026-07-04 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_safe_date_spot', models.BooleanField(default=False)),
                ('safety_score', models.IntegerField(default=0)),
                ('safety_criteria', models.JSONField(blank=True, default=dict)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsor_discount', models.CharField(blank=True, max_length=255)),
                ('sponsor_perks', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='venues.venuecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
