# Generated by Django 5.1.15 on 2026-06-23 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.IntegerField(choices=[(1, 'candidate'), (2, 'twin_chat'), (3, 'ready_to_reveal'), (4, 'revealed')], default=1)),
                ('stage_1_score', models.FloatField(blank=True, null=True)),
                ('stage_2_score', models.FloatField(blank=True, null=True)),
                ('stage_3_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('revealed', 'Revealed'), ('declined', 'Declined')], default='pending', max_length=32)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_score', models.FloatField()),
                ('character_score', models.FloatField()),
                ('lifestyle_score', models.FloatField()),
                ('values_score', models.FloatField()),
                ('career_score', models.FloatField()),
                ('hobbies_score', models.FloatField()),
                ('detailed_analysis', models.JSONField(default=dict)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_report', to='matching.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_match_pair'),
        ),
    ]
